@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"name": "Kaiser",
	"email": "kaiser@kaiserinc.com.br",
	"password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "kaiser@kaiserinc.com.br",
	"password": "12345678"
}

###

# @name create_quest
POST {{baseUrl}}/quests
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "The architect masterpiece 5",
	"description": "Create a gamified system for habbit tracking and self inprovment"
}

###

# @name fetch_quests
GET {{baseUrl}}/quests?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

